### ISSUE TITLE
Configuration takes over 3.5GB of memory

### ISSUE THREAD

**Issue by marceldekoning** [ActiveCampaign/module-integration#25]
When opening the system configuration, over 3.5GB of memory is used to open just this section and because the sort order is at 1, the configuration page can't be opened anymore when no more memory is available.

Magento version: 2.3.4
Active Campaign module version: 2.0.4
PHP Version: 7.3

**Comment by JelleGe** [comment]
Hi Marcel,

There is a easy fix for this:

Open the file `ActiveCampaign/Core/etc/adminhtml/system.xml` and change the lines 4-6 into the following:

```
        <tab id="active_campaign" translate="label" sortOrder="99999">
            <label>ActiveCampaign</label>
        </tab>
```

That should do the trick, because you change the sortOrder for this menu item in your configuration page.

**Comment by marceldekoning** [comment]
@JelleGe,

This is off course not a solution, but simply moving the initial problem to a different section. I would really like to hear why so much memory is used, and how we can solve that.

**Comment by JelleGe** [comment]
@marceldekoning 

For sure, that should be solved by the module itself, but it's a pretty good work around in the meantime.

**Comment by JoostWan** [comment]
When your store has a lot of orders the performance of the tab is very slow. This is because of the page load it calculates the amount of orders, customers etc. 

https://github.com/ActiveCampaign/module-integration/blob/189e2a67c50c7c88220db795a93f141c3b33e2cd/Order/view/adminhtml/templates/system/config/order_sync_status.phtml

https://github.com/ActiveCampaign/module-integration/blob/189e2a67c50c7c88220db795a93f141c3b33e2cd/Order/Block/Adminhtml/System/Config/OrderSyncStatus.php#L46

**Comment by shaughnlgh** [comment]
I have a fix for this, related to PR: https://github.com/ActiveCampaign/module-integration/pull/35

**Comment by jordan-price** [comment]
This has been merged in and will go out in the next release to the Adobe marketplace.
